### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by JaraR** [JaraR/DarkPatternDetector#15]

**Comment by Jiaxin-Liu04** [comment]
Persona Description:
Digital Media Professional - Maria (28 years old)
"Maria is a 28-year-old Digital Marketing Manager. Her daily work involves crafting campaigns that effectively engage users while avoiding manipulative tactics. She's aware of how dark patterns influence behavior on social platforms, and she wants to create more ethical marketing strategies. Maria values maintaining high user trust and engagement without relying on emotional manipulation."

Concerned Parent - Wesley (45 years old)
"Wesley, a 45-year-old working father, is deeply concerned about his 12-year-old child's online safety. He uses the extension to identify harmful or emotionally manipulative content that his child might encounter on social media. Wesley is committed to protecting his child and gaining better awareness of how platforms influence young users' decisions."

Teenager - Max (16 years old)
"Max is a 16-year-old high school student who spends a lot of time on social media. Although he's tech-savvy, he's not always aware of how platforms use dark patterns to manipulate his behavior. Max uses the extension to understand better how social media might influence his decisions and to take more control over his online experiences."

Tech Professional - Tom (26 years old)
"Tom, a 26-year-old software engineer, is highly skilled in technology. He uses the extension to monitor the ethical design of platforms and better understand how dark patterns work from a technical standpoint. Tom is passionate about creating software that respects users’ autonomy and avoids manipulative design practices."
