### ISSUE TITLE
Dark pattern types on social media research

### ISSUE THREAD

**Issue by lingjiang9** [JaraR/DarkPatternDetector#22]

**Comment by JaraR** [comment]
Rough draft shown to Andrea, asked to pick a few (roughly 7) that are specific to X, prioritize those, update matrix, and return for feedback by Tuesday evening.

**Comment by JaraR** [comment]
Many dark patterns listed on word doc that was shown to Andrea on 30-01-2024.

**Comment by JaraR** [comment]
Tentative final list of 7 dark patterns to detect on X/Twitter decided on 02-10-2024.

**Comment by JaraR** [comment]
Seven dark patterns decided on and shown on the 04/10/2024 presentation:

Privacy Zuckering​

Infinite Scrolling​

Emotional Steering​

Autoplay​

Obstructing/content buried​

Engagement notifications​

Promoted Tweets and Ads that Blend In
