### ISSUE TITLE
Demo a similar system

### ISSUE THREAD

**Issue by lingjiang9** [JaraR/DarkPatternDetector#25]

**Comment by JaraR** [comment]
Similar systems were found, researched, and prepared by 03/10/2024 for presentation on 04/10/2024. Systems chosen for demoing were the Grammarly and ToS;DR chrome extensions. Other systems found but not demoed were:
https://github.com/NicholasTung/dark-patterns-recognition
https://dapde.de/en/   |   https://github.com/Dapde/Pattern-Highlighter
https://chromewebstore.google.com/detail/insite-highlighter/lpibfdnafmhjjjbglaedkbegelnllibc

**Comment by lingjiang9** [comment]
Well done on identifying and researching similar systems. We can analyze their features, design and approaches to refine and design our own system more effectively
